package com.jshuabo.templateadminmysql.server.dao.channel;

import com.jshuabo.frame.server.dao.IBaseMapper;
import com.jshuabo.templateadminmysql.server.model.channel.ChannelInfo;

public interface ChannelInfoMapper extends IBaseMapper<ChannelInfo> {
    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_info
     *
     * @mbggenerated
     */
    int deleteByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_info
     *
     * @mbggenerated
     */
    int insert(ChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_info
     *
     * @mbggenerated
     */
    int insertSelective(ChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_info
     *
     * @mbggenerated
     */
    ChannelInfo selectByPrimaryKey(Long id);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKeySelective(ChannelInfo record);

    /**
     * This method was generated by MyBatis Generator.
     * This method corresponds to the database table t_channel_info
     *
     * @mbggenerated
     */
    int updateByPrimaryKey(ChannelInfo record);
}